[2021-04-25 20:59:02,334] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: customer_360_pipeline.watch_for_orders 2021-04-24T00:00:00+00:00 [queued]>
[2021-04-25 20:59:02,339] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: customer_360_pipeline.watch_for_orders 2021-04-24T00:00:00+00:00 [queued]>
[2021-04-25 20:59:02,340] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 20:59:02,340] {taskinstance.py:1069} INFO - Starting attempt 1 of 13
[2021-04-25 20:59:02,340] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 20:59:02,426] {taskinstance.py:1089} INFO - Executing <Task(HttpSensor): watch_for_orders> on 2021-04-24T00:00:00+00:00
[2021-04-25 20:59:02,428] {standard_task_runner.py:52} INFO - Started process 14293 to run task
[2021-04-25 20:59:02,432] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'customer_360_pipeline', 'watch_for_orders', '2021-04-24T00:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpx0ghph2u', '--error-file', '/tmp/tmpwk38gi49']
[2021-04-25 20:59:02,434] {standard_task_runner.py:77} INFO - Job 2: Subtask watch_for_orders
[2021-04-25 20:59:02,593] {logging_mixin.py:104} INFO - Running <TaskInstance: customer_360_pipeline.watch_for_orders 2021-04-24T00:00:00+00:00 [running]> on host gaurav-MS-7B84
[2021-04-25 20:59:02,683] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_360_pipeline
AIRFLOW_CTX_TASK_ID=watch_for_orders
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-24T00:00:00+00:00
[2021-04-25 20:59:02,683] {http.py:102} INFO - Poking: orders.csv
[2021-04-25 20:59:02,692] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/sensors/base.py", line 228, in execute
    while not self.poke(context):
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/providers/http/sensors/http.py", line 118, in poke
    raise exc
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/providers/http/sensors/http.py", line 108, in poke
    extra_options=self.extra_options,
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 122, in run
    session = self.get_conn(headers)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 72, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `order_s3` isn't defined
[2021-04-25 20:59:02,694] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=customer_360_pipeline, task_id=watch_for_orders, execution_date=20210424T000000, start_date=20210425T152902, end_date=20210425T152902
[2021-04-25 20:59:02,804] {local_task_job.py:146} INFO - Task exited with return code 1
